### ISSUE TITLE
1.9.4 compatible

### ISSUE THREAD

**Issue by SnowWalkerJ** [Nuclearsmilz/SecretRoomsMod-1.11.2#1]
It's an amazing mod. It's a pity to see the original author has stopped maintaining it.

Great to see that you have updated it to be compatible with 1.11.2. But I am running 1.9.4 currently. So is this compatible? Or do I have to make certain changes to make it work? I am new in mod programming.

**Comment by jondmarien** [comment]
It will not be compatible with 1.9.4 unfortunately, as it is not a popular version. I will also not be back-porting, especially since 1.12 has been released. This version is also incomplete.
